# active spring boot profile
spring:
   profiles:
      active: development

---
# common spring boot configuration
spring:
   mvc:
      # Path pattern used for static resources
      static-path-pattern: /assets/**

      # Whether a "NoHandlerFoundException" should be thrown if no Handler was found to process a request
      throw-exception-if-no-handler-found: true
   web:
      resources:
         # Locations of static resources
         static-locations: classpath:/static/

   thymeleaf:
      prefix : classpath:templates/
      check-template-location: true
      mode: HTML5
      suffix : .html
      cache : false

   # datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.0.197:3307/webdb?characterEncoding=utf8
      username: webdb
      password: webdb


---
# development profile: spring boot configuration
spring:
   config:
      activate:
         on-profile: development

   # devtools - live reload
   devtools:
      livereload:
         enabled: true


---
# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

   
---
# server
server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
         
---
# logging
logging:
   level:
      root: WARN
      